name: "Provision AKS cluster"
on:
  workflow_dispatch:
env:
    LOCATION: westus2
    RESOURCE_GROUP_NAME: zimagi-rg
    AKS_CLUSTER_NAME: zimagi-aks
jobs:
  provision_backend:
    name: "Provision azure backend"
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create azure backend
        run: |
          az group create --name ${{ env.TF_RESOURCE_GROUP_NAME }} --location ${{ env.LOCATION }}
          az storage account create -n $TF_STORAGE_ACCOUNT_NAME -g $TF_RESOURCE_GROUP_NAME -l $LOCATION --sku Standard_LRS
          az storage container create -n terraform-state --account-name $TF_STORAGE_ACCOUNT_NAME
        env:
          TF_RESOURCE_GROUP_NAME: "zimagi-tf"
          TF_STORAGE_ACCOUNT_NAME: "zimagitfbackend"

  terraform_apply:
    name: "Terraform Apply"
    needs: [provision_backend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aks
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Install terraform cli"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25

      - name: "Terraform format"
        run: terraform fmt -check -no-color
        continue-on-error: false

      - name: "Terraform Init"
        run: terraform init
        continue-on-error: false
        
      - name: "Terraform Validate"
        run: terraform validate -no-color
        continue-on-error: false

      - name: "Terraform Plan"
        run: terraform plan -no-color
        continue-on-error: false

      - name: "Terraform Apply"
        run: terraform apply -no-color -auto-approve
        continue-on-error: false
      
  deploy_ingress_controller:
    name: "Deploy application gateway ingress controller"
    needs: [provision_backend, terraform_apply]
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.8'

      - uses: azure/setup-helm@v1
        with:
          version: 'v3.4.0'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy ingress controller"
        run: |
          PUBLIC_IP_ADDRESS=$(az network public-ip create --resource-group MC_${RESOURCE_GROUP_NAME}_${AKS_CLUSTER_NAME}_${LOCATION} --location westus2 --name zimagi-agic --sku Standard --allocation-method static --query publicIp.ipAddress -o=tsv)
          az aks get-credentials \
            --name ${AKS_CLUSTER_NAME} \
            --resource-group ${RESOURCE_GROUP_NAME}

          kubectl create namespace nginx-ingress

          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add jetstack https://charts.jetstack.io
          helm repo update

          helm install nginx-ingress ingress-nginx/ingress-nginx \
              --namespace nginx-ingress \
              --set controller.replicaCount=2 \
              --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
              --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux \
              --set controller.admissionWebhooks.patch.nodeSelector."beta\.kubernetes\.io/os"=linux \
              --set controller.service.loadBalancerIP=${PUBLIC_IP_ADDRESS} \
              --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="zimagi"

          kubectl label namespace nginx-ingress cert-manager.io/disable-validation=true

          helm install \
            cert-manager \
            --namespace nginx-ingress \
            --version v0.16.1 \
            --set installCRDs=true \
            --set nodeSelector."beta\.kubernetes\.io/os"=linux \
            jetstack/cert-manager

          # Wait until cert manager will be available
          sleep 60

          kubectl apply -f ./aks/k8s/cluster-issuer.yaml          